# Generated by Django 4.2 on 2023-04-25 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('stripe_price_id', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=300)),
                ('provincia', models.CharField(max_length=300)),
                ('codigo_p', models.IntegerField(blank=True, null=True)),
                ('ciudad', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stripe_subscription_id', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='inmuebles.pricing')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_de_inmueble', models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Local', 'Local'), ('Oficina', 'Oficina'), ('Bodega', 'Bodega'), ('Vivienda vacacional', 'Vivienda vacacional')], default='Casa', max_length=100)),
                ('operacion', models.CharField(choices=[('Venta', 'Venta'), ('Arriendo', 'Arriendo'), ('Permuta', 'Permuta')], default='Venta', max_length=100)),
                ('precio', models.BigIntegerField()),
                ('estado', models.CharField(choices=[('Obra nueva', 'Obra nueva'), ('Usado', 'Usado')], default='Obra nueva', max_length=30)),
                ('portada', models.ImageField(upload_to='media/inmuebles/portadas/%Y/%m/%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/inmuebles/videos/%Y/%m/%d')),
                ('area', models.PositiveIntegerField()),
                ('habitaciones', models.PositiveIntegerField()),
                ('banos', models.CharField(max_length=6)),
                ('valor_administracion', models.CharField(blank=True, max_length=200, null=True)),
                ('estrato', models.PositiveIntegerField(blank=True, null=True)),
                ('antiguedad', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('parqueadero', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False)),
                ('zonas_verdes', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False)),
                ('zonas_ninos', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False)),
                ('zona_comercial', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False)),
                ('zona_residencial', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False)),
                ('estudio', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=255, unique=True, unique_for_date='published')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('image', models.ManyToManyField(blank=True, to='inmuebles.image')),
                ('pricing_tiers', models.ManyToManyField(blank=True, to='inmuebles.pricing')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.ubicacion')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
