# Generated by Django 4.2 on 2023-05-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0004_plan_description_suscripcion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='Lat',
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='Lng',
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='ubicacion',
            field=models.TextField(),
        ),
    ]
