# Generated by Django 4.2 on 2023-05-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0006_plan_paypal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='paypal_plan_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
