# Generated by Django 4.2 on 2023-05-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0007_plan_paypal_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='ba_token',
            field=models.CharField(blank=True, max_length=560),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='id_suscripcion',
            field=models.CharField(blank=True, max_length=560),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='token',
            field=models.CharField(blank=True, max_length=560),
        ),
    ]
