# Generated by Django 4.2 on 2023-05-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_creditcardtokenid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payer_id_paypal',
            field=models.TextField(blank=True),
        ),
    ]
