# Generated by Django 4.2 on 2023-05-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apellidos',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nombres',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
